/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.views;

import org.example.estructuras.LinkedList;
import org.example.models.ServicioCulminado;
import org.example.models.ServicioEnEjecucion;
import org.example.services.FacturasService;
import org.example.services.ServiciosService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class ServiciosForm extends javax.swing.JDialog {
    JTable target    = new JTable();
    static int row   = -1;

    /**
     * Creates new form ServiciosForm
     */
    public ServiciosForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
    }

    private void llenarTablaServiciosCulminados(LinkedList<ServicioCulminado> servicios){
        DefaultTableModel modeloT = (DefaultTableModel) tabla_serviciosCulminados.getModel();
        for (int i = modeloT.getRowCount() - 1; i >= 0; i--) {
            modeloT.removeRow(i);
        }
        if(servicios.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay datos para mostrar");
            return;
        }

        for (ServicioCulminado servicio: servicios) {
            String centro = servicio.getSolicitud().getCentro().getNombre();
            String taxi = servicio.getTaxi().getId();
            String recogida = servicio.getSolicitud().getDireccion();
            String destino = servicio.getSolicitud().getDestino();
            String horaInicio = String.valueOf(servicio.getSolicitud().getHora());
            String horaFin = String.valueOf(servicio.getHoraFin());
            float distancia = servicio.getSolicitud().getCantKm();

            Object[] datos = {centro, taxi, recogida, destino, horaInicio, horaFin, distancia};
            modeloT.addRow(datos);
        }
    }

    private void llenarTablaServiciosEnEjecucion(LinkedList<ServicioEnEjecucion> servicios){
        DefaultTableModel modeloT = (DefaultTableModel) tabla_serviciosEnEjecucion.getModel();
        for (int i = modeloT.getRowCount() - 1; i >= 0; i--) {
            modeloT.removeRow(i);
        }
        if(servicios.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay datos para mostrar");
            return;
        }

        for (ServicioEnEjecucion servicio: servicios) {
            String centro = servicio.getSolicitud().getCentro().getNombre();
            String taxi = servicio.getTaxi().getId();
            String recogida = servicio.getSolicitud().getDireccion();
            String destino = servicio.getSolicitud().getDestino();
            String hora = String.valueOf(servicio.getSolicitud().getHora());

            Object[] datos = {centro, taxi, recogida, destino, hora};
            modeloT.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        panel_serviciosEnEjecucion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_serviciosEnEjecucion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JButton();
        btn_cancelarServicio = new javax.swing.JButton();
        btn_maracarServicioTerminado = new javax.swing.JButton();
        panel_serviciosCulminados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_serviciosCulminados = new javax.swing.JTable();
        btn_generarFacturas = new javax.swing.JButton();
        btn_Atras_serviciosCulminados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        tabla_serviciosEnEjecucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Centro", "Taxi", "Recogida", "Destino", "Hora_Inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_serviciosEnEjecucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_serviciosEnEjecucionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_serviciosEnEjecucion);
        if (tabla_serviciosEnEjecucion.getColumnModel().getColumnCount() > 0) {
            tabla_serviciosEnEjecucion.getColumnModel().getColumn(0).setResizable(false);
            tabla_serviciosEnEjecucion.getColumnModel().getColumn(1).setResizable(false);
            tabla_serviciosEnEjecucion.getColumnModel().getColumn(2).setResizable(false);
            tabla_serviciosEnEjecucion.getColumnModel().getColumn(3).setResizable(false);
            tabla_serviciosEnEjecucion.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servicios en Ejecución");

        btn_Atras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Atras.setText("Atrás");
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });

        btn_cancelarServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cancelarServicio.setText("Cancelar Servicio");
        btn_cancelarServicio.setEnabled(false);
        btn_cancelarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarServicioActionPerformed(evt);
            }
        });

        btn_maracarServicioTerminado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_maracarServicioTerminado.setText("Marcar como terminado");
        btn_maracarServicioTerminado.setEnabled(false);
        btn_maracarServicioTerminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maracarServicioTerminadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_serviciosEnEjecucionLayout = new javax.swing.GroupLayout(panel_serviciosEnEjecucion);
        panel_serviciosEnEjecucion.setLayout(panel_serviciosEnEjecucionLayout);
        panel_serviciosEnEjecucionLayout.setHorizontalGroup(
            panel_serviciosEnEjecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_serviciosEnEjecucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_serviciosEnEjecucionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_cancelarServicio)
                .addGap(18, 18, 18)
                .addComponent(btn_maracarServicioTerminado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Atras)
                .addGap(40, 40, 40))
        );
        panel_serviciosEnEjecucionLayout.setVerticalGroup(
            panel_serviciosEnEjecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_serviciosEnEjecucionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panel_serviciosEnEjecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atras)
                    .addComponent(btn_cancelarServicio)
                    .addComponent(btn_maracarServicioTerminado))
                .addGap(34, 34, 34))
        );

        tabbedPanel.addTab("Servcios en Ejecución", panel_serviciosEnEjecucion);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Servicios Culminados");

        tabla_serviciosCulminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Centro", "Taxi", "Recogida", "Destino", "Hora_Inicio", "Hora_Fin", "Distancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_serviciosCulminados);
        if (tabla_serviciosCulminados.getColumnModel().getColumnCount() > 0) {
            tabla_serviciosCulminados.getColumnModel().getColumn(0).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(1).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(2).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(3).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(4).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(5).setResizable(false);
            tabla_serviciosCulminados.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_generarFacturas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_generarFacturas.setText("Generar Facturas");
        btn_generarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarFacturasActionPerformed(evt);
            }
        });

        btn_Atras_serviciosCulminados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Atras_serviciosCulminados.setText("Atrás");
        btn_Atras_serviciosCulminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Atras_serviciosCulminadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_serviciosCulminadosLayout = new javax.swing.GroupLayout(panel_serviciosCulminados);
        panel_serviciosCulminados.setLayout(panel_serviciosCulminadosLayout);
        panel_serviciosCulminadosLayout.setHorizontalGroup(
            panel_serviciosCulminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_serviciosCulminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_serviciosCulminadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_generarFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Atras_serviciosCulminados)
                .addGap(35, 35, 35))
        );
        panel_serviciosCulminadosLayout.setVerticalGroup(
            panel_serviciosCulminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_serviciosCulminadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panel_serviciosCulminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generarFacturas)
                    .addComponent(btn_Atras_serviciosCulminados))
                .addGap(36, 36, 36))
        );

        tabbedPanel.addTab("Servcios Culminados", panel_serviciosCulminados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarServicioActionPerformed
        if (row >= 0){
            ServiciosService.cancelarServicioEnEjecucion(row);
        }
        row = -1;
        btn_maracarServicioTerminado.setEnabled(false);
        btn_cancelarServicio.setEnabled(false);
        llenarTablaServiciosEnEjecucion(ServiciosService.getServciosEnEjecucion());
    }//GEN-LAST:event_btn_cancelarServicioActionPerformed

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void btn_generarFacturasActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_btn_generarFacturasActionPerformed
        FacturasService.generarFaturas(ServiciosService.getServiciosCulminados());
    }//GEN-LAST:event_btn_generarFacturasActionPerformed

    private void btn_Atras_serviciosCulminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Atras_serviciosCulminadosActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_Atras_serviciosCulminadosActionPerformed

    private void tabla_serviciosEnEjecucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_serviciosEnEjecucionMouseClicked
        if (evt.getClickCount() == 1) {  //Si se hizo un click
            target = (JTable) evt.getSource();
            row    = target.getSelectedRow(); // Obtener la fila

            btn_cancelarServicio.setEnabled(true);
            btn_maracarServicioTerminado.setEnabled(true);
        }
    }//GEN-LAST:event_tabla_serviciosEnEjecucionMouseClicked

    private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
        if (tabbedPanel.getSelectedIndex() == 0)
            llenarTablaServiciosEnEjecucion(ServiciosService.getServciosEnEjecucion());
        else
            llenarTablaServiciosCulminados(ServiciosService.getServiciosCulminados());
    }//GEN-LAST:event_tabbedPanelStateChanged

    private void btn_maracarServicioTerminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maracarServicioTerminadoActionPerformed
        if (row >= 0){
            ServiciosService.marcarServicioComoTerminado(ServiciosService.getServciosEnEjecucion().get(row));
        }
        row = -1;
        btn_maracarServicioTerminado.setEnabled(false);
        btn_cancelarServicio.setEnabled(false);
        llenarTablaServiciosEnEjecucion(ServiciosService.getServciosEnEjecucion());
    }//GEN-LAST:event_btn_maracarServicioTerminadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiciosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiciosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiciosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiciosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiciosForm dialog = new ServiciosForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_Atras_serviciosCulminados;
    private javax.swing.JButton btn_cancelarServicio;
    private javax.swing.JButton btn_generarFacturas;
    private javax.swing.JButton btn_maracarServicioTerminado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_serviciosCulminados;
    private javax.swing.JPanel panel_serviciosEnEjecucion;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tabla_serviciosCulminados;
    private javax.swing.JTable tabla_serviciosEnEjecucion;
    // End of variables declaration//GEN-END:variables
}
