package org.example.views;

import org.example.estructuras.LinkedList;
import org.example.models.Taxi;
import org.example.models.TaxiEstatal;
import org.example.models.TaxiParticular;
import org.example.services.TaxisService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author jorge
 */
public class TaxiForm extends javax.swing.JDialog {
    JTable target    = new JTable();
    static int row   = -1;

    public TaxiForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla(TaxisService.getTaxis());
        setVisible(true);
    }
    
    private void llenarTabla(LinkedList<Taxi> taxis){
        DefaultTableModel modeloT = (DefaultTableModel) tablaTaxis.getModel();
        for (int i = modeloT.getRowCount() - 1; i >= 0; i--) {
            modeloT.removeRow(i);
        }
        if(taxis.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay datos para mostrar");
            return;
        }
        System.out.println(taxis);
        for (Taxi taxi: taxis) {
            String chapa = taxi.getId();
            String marca = taxi.getMarca();
            String estado = taxi.getEstado();
            int capacidad = taxi.getCapacidad();
            String chofer = taxi.getChofer();
            float km = taxi.getCombustible();
            String empresa, patente;
            Object[] datos;
            if(taxi instanceof TaxiEstatal){
                empresa = ((TaxiEstatal)taxi).getEmpresa();
                datos = new Object[]{chapa, marca, estado, capacidad, chofer, km, empresa, "  -  "};
            }else{
                patente = ((TaxiParticular)taxi).getNoPatente();
                datos = new Object[]{chapa, marca, estado, capacidad, chofer, km, "  -  ", patente};
            }
            modeloT.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTaxis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_registrarTaxi = new javax.swing.JButton();
        btn_editarTaxi = new javax.swing.JButton();
        btn_eliminarTaxi = new javax.swing.JButton();
        btn_AtrasTaxiForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaTaxis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chapa", "Marca", "Estado", "Capacidad", "Chofer", "Combustible", "Empresa", "No. patente"
            }
        ));
        tablaTaxis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTaxisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTaxis);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Gestion de Taxis");

        btn_registrarTaxi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_registrarTaxi.setText("Registrar Taxi");
        btn_registrarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarTaxiActionPerformed(evt);
            }
        });

        btn_editarTaxi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_editarTaxi.setText("Editar Taxi");
        btn_editarTaxi.setEnabled(false);
        btn_editarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarTaxiActionPerformed(evt);
            }
        });

        btn_eliminarTaxi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_eliminarTaxi.setText("Eliminar Taxi");
        btn_eliminarTaxi.setEnabled(false);
        btn_eliminarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarTaxiActionPerformed(evt);
            }
        });

        btn_AtrasTaxiForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_AtrasTaxiForm.setText("Atrás");
        btn_AtrasTaxiForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasTaxiFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_registrarTaxi)
                                .addGap(37, 37, 37)
                                .addComponent(btn_editarTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_eliminarTaxi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_AtrasTaxiForm))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrarTaxi)
                    .addComponent(btn_editarTaxi)
                    .addComponent(btn_eliminarTaxi)
                    .addComponent(btn_AtrasTaxiForm))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarTaxiActionPerformed
        CrearTaxiForm crearTaxiForm = new CrearTaxiForm((Frame) this.getParent(), true, null);
        llenarTabla(TaxisService.getTaxis());
    }//GEN-LAST:event_btn_registrarTaxiActionPerformed

    private void btn_editarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarTaxiActionPerformed
        CrearTaxiForm crearTaxiForm = new CrearTaxiForm((Frame) this.getParent(), true, TaxisService.getTaxis().get(row));

        row = -1;
        btn_editarTaxi.setEnabled(false);
        btn_eliminarTaxi.setEnabled(false);
        llenarTabla(TaxisService.getTaxis());
    }//GEN-LAST:event_btn_editarTaxiActionPerformed

    private void btn_eliminarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarTaxiActionPerformed
        TaxisService.eliminartaxi(TaxisService.getTaxis().get(row).getId());

        row = -1;
        btn_editarTaxi.setEnabled(false);
        btn_eliminarTaxi.setEnabled(false);
        llenarTabla(TaxisService.getTaxis());
    }//GEN-LAST:event_btn_eliminarTaxiActionPerformed

    private void btn_AtrasTaxiFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasTaxiFormActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AtrasTaxiFormActionPerformed

    private void tablaTaxisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTaxisMouseClicked
        if (evt.getClickCount() == 1) {  //Si se hizo un click
            target = (JTable) evt.getSource();
            row    = target.getSelectedRow(); // Obtener la fila

            btn_editarTaxi.setEnabled(true);
            btn_eliminarTaxi.setEnabled(true);
        }    }//GEN-LAST:event_tablaTaxisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaxiForm dialog = null;
                dialog = new TaxiForm(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AtrasTaxiForm;
    private javax.swing.JButton btn_editarTaxi;
    private javax.swing.JButton btn_eliminarTaxi;
    private javax.swing.JButton btn_registrarTaxi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTaxis;
    // End of variables declaration//GEN-END:variables
}
